//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itanio.SessaoAoVivo.ServicosAplicacao.GravadorArquivoServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArquivoDTO", Namespace="http://schemas.datacontract.org/2004/07/Itanio.SessaoAoVivo.WCF.ServicosWeb")]
    [System.SerializableAttribute()]
    public partial class ArquivoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ConteudoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Conteudo {
            get {
                return this.ConteudoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConteudoField, value) != true)) {
                    this.ConteudoField = value;
                    this.RaisePropertyChanged("Conteudo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GravadorArquivoServices.IGravadorArquivoService")]
    public interface IGravadorArquivoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGravadorArquivoService/Salvar", ReplyAction="http://tempuri.org/IGravadorArquivoService/SalvarResponse")]
        void Salvar(Itanio.SessaoAoVivo.ServicosAplicacao.GravadorArquivoServices.ArquivoDTO arquivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGravadorArquivoService/Salvar", ReplyAction="http://tempuri.org/IGravadorArquivoService/SalvarResponse")]
        System.Threading.Tasks.Task SalvarAsync(Itanio.SessaoAoVivo.ServicosAplicacao.GravadorArquivoServices.ArquivoDTO arquivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGravadorArquivoService/Obter", ReplyAction="http://tempuri.org/IGravadorArquivoService/ObterResponse")]
        byte[] Obter(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGravadorArquivoService/Obter", ReplyAction="http://tempuri.org/IGravadorArquivoService/ObterResponse")]
        System.Threading.Tasks.Task<byte[]> ObterAsync(string nome);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGravadorArquivoServiceChannel : Itanio.SessaoAoVivo.ServicosAplicacao.GravadorArquivoServices.IGravadorArquivoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GravadorArquivoServiceClient : System.ServiceModel.ClientBase<Itanio.SessaoAoVivo.ServicosAplicacao.GravadorArquivoServices.IGravadorArquivoService>, Itanio.SessaoAoVivo.ServicosAplicacao.GravadorArquivoServices.IGravadorArquivoService {
        
        public GravadorArquivoServiceClient() {
        }
        
        public GravadorArquivoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GravadorArquivoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GravadorArquivoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GravadorArquivoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Salvar(Itanio.SessaoAoVivo.ServicosAplicacao.GravadorArquivoServices.ArquivoDTO arquivo) {
            base.Channel.Salvar(arquivo);
        }
        
        public System.Threading.Tasks.Task SalvarAsync(Itanio.SessaoAoVivo.ServicosAplicacao.GravadorArquivoServices.ArquivoDTO arquivo) {
            return base.Channel.SalvarAsync(arquivo);
        }
        
        public byte[] Obter(string nome) {
            return base.Channel.Obter(nome);
        }
        
        public System.Threading.Tasks.Task<byte[]> ObterAsync(string nome) {
            return base.Channel.ObterAsync(nome);
        }
    }
}
